// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsEndpoint) DeepCopyInto(out *MetricsEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsEndpoint.
func (in *MetricsEndpoint) DeepCopy() *MetricsEndpoint {
	if in == nil {
		return nil
	}
	out := new(MetricsEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporter) DeepCopyInto(out *PrometheusJmxExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporter.
func (in *PrometheusJmxExporter) DeepCopy() *PrometheusJmxExporter {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusJmxExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporterConfig) DeepCopyInto(out *PrometheusJmxExporterConfig) {
	*out = *in
	if in.StartDelaySeconds != nil {
		in, out := &in.StartDelaySeconds, &out.StartDelaySeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int)
			**out = **in
		}
	}
	if in.HostPort != nil {
		in, out := &in.HostPort, &out.HostPort
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.JmxUrl != nil {
		in, out := &in.JmxUrl, &out.JmxUrl
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Ssl != nil {
		in, out := &in.Ssl, &out.Ssl
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	if in.LowercaseOutputName != nil {
		in, out := &in.LowercaseOutputName, &out.LowercaseOutputName
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	if in.LowercaseOutputLabelNames != nil {
		in, out := &in.LowercaseOutputLabelNames, &out.LowercaseOutputLabelNames
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	if in.WhitelistObjectNames != nil {
		in, out := &in.WhitelistObjectNames, &out.WhitelistObjectNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlacklistObjectNames != nil {
		in, out := &in.BlacklistObjectNames, &out.BlacklistObjectNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PrometheusJmxExporterConfigRules, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporterConfig.
func (in *PrometheusJmxExporterConfig) DeepCopy() *PrometheusJmxExporterConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporterConfigRules) DeepCopyInto(out *PrometheusJmxExporterConfigRules) {
	*out = *in
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.ValueFactor != nil {
		in, out := &in.ValueFactor, &out.ValueFactor
		if *in == nil {
			*out = nil
		} else {
			*out = new(float32)
			**out = **in
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Help != nil {
		in, out := &in.Help, &out.Help
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.AttrNameSnakeCase != nil {
		in, out := &in.AttrNameSnakeCase, &out.AttrNameSnakeCase
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporterConfigRules.
func (in *PrometheusJmxExporterConfigRules) DeepCopy() *PrometheusJmxExporterConfigRules {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporterConfigRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporterList) DeepCopyInto(out *PrometheusJmxExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrometheusJmxExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporterList.
func (in *PrometheusJmxExporterList) DeepCopy() *PrometheusJmxExporterList {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusJmxExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporterSpec) DeepCopyInto(out *PrometheusJmxExporterSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Config = in.Config
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporterSpec.
func (in *PrometheusJmxExporterSpec) DeepCopy() *PrometheusJmxExporterSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusJmxExporterStatus) DeepCopyInto(out *PrometheusJmxExporterStatus) {
	*out = *in
	if in.MetricsEndpoints != nil {
		in, out := &in.MetricsEndpoints, &out.MetricsEndpoints
		*out = make([]*MetricsEndpoint, len(*in))
		for i := range *in {
			if (*in)[i] == nil {
				(*out)[i] = nil
			} else {
				(*out)[i] = new(MetricsEndpoint)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusJmxExporterStatus.
func (in *PrometheusJmxExporterStatus) DeepCopy() *PrometheusJmxExporterStatus {
	if in == nil {
		return nil
	}
	out := new(PrometheusJmxExporterStatus)
	in.DeepCopyInto(out)
	return out
}
